backchannelapp/config/routes.rb
Backchannelapp::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :posts

  resources :comments

  resources :votes

  match 'posts/search',:to => 'posts#search'
  match 'users/report', :to => 'users#report'

  root :to => 'welcome#index'

   match ':controller(/:action(/:id))(.:format)'
end

backchannelapp/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :category, :created_at, :message, :user_id, :commented, :category_id
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  validates_presence_of :user_id, :message, :created_at, :category_id
  belongs_to :category
  #serialize :message, :category

  def self.find_by_content(content)
    #Post.all(:conditions => ["message like ?", "%#{content}%"])
    Post.where("message LIKE ?", "%#{content}%" )
  end

  def self.find_by_uid(user_id)
    Post.all(:conditions => {:user_id => user_id})
  end

  def self.find_by_cid(category_id)
    Post.all(:conditions => {:category_id => category_id})
  end
end

backchannelapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
         @all_posts = Post.all(:order => "created_at")
    end

    def create
      @post = Post.new(params[:post])
      #@post.category = params[:category]
      @post.user_id = current_user.id
      @post.created_at = Time.now
      @post.commented = 0

      respond_to do |format|
       if @post.save
         format.html {redirect_to posts_path, :notice => "Post successfully submitted"}
      else
        format.html {redirect_to new_post_path, :notice => "Failed to submit post"}
      end
      end
    end

    def new
      @post = Post.new
      @category = Category.all
      respond_to do |format|
        format.html # new.html.erb
      end

    end

    def destroy
      @post = Post.find(params[:id])
      respond_to do |format|
      if @post.destroy
        format.html {redirect_to posts_path, :notice => "Post successfully deleted"}
      else
        format.html {redirect_to posts_path, :notice => "Failed to delete post"}
      end
      end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      respond_to do |format|
        if @post.update_attributes(params[:post], :category => params[:category], :created_at => Time.now)
          format.html {redirect_to posts_path, :notice => "Post successfully updated"}
        else
          format.html {redirect_to posts_path, :notice => "Failed to update post"}
        end
      end
    end

    def show
      @post = Post.find(params[:id])
      #if @post.commented == 1
        @comments = Comment.all(:conditions => {:post_id => @post.id}, :order => "created_at DESC")
        #@comment = Comment.all
      #end
    end

    def create_vote
      @vote = Vote.new(:post_id => params[:post_id], :user_id => current_user.id, :created_at => Time.now)
      respond_to do |format|
      if @vote.save
        @post = Post.find(params[:post_id])
        @post.update_attributes(:created_at => Time.now)
        format.html {redirect_to posts_path, :notice => "Voted for post successfully"}
      else
        format.html {redirect_to posts_path, :notice => "Failed to save vote"}
      end
      end
    end

    def search
      @search = params[:search]
      @results = Post.find_by_content(@search)

      @user = User.where("username LIKE ?", "%#{params[:search]}%")
      @user.each do |u|
        @post_user = Post.find_by_uid(u.id)
          @post_user.each do |p|
            @results << p
          end
      end
      @cats = Category.where("category LIKE ?", "%#{params[:search]}%")
      @cats.each do |c|
        @post_cat = Post.find_by_cid(c.id)
          @post_cat.each do |p|
            @results << p
          end
      end
      @results = @results.all.uniq
    end
end

backchannelapp/app/helpers/posts_helper.rb
module PostsHelper
  def can_vote?(post_id)
    @votes = Vote.all(:conditions => {:post_id => post_id})
    @votes.each do |v|
      if v.user_id == session[:user_id]
        return false
      end
    end
    return true
  end

  def num_votes(post_id)
    @votes = Vote.all(:conditions => {:post_id => post_id})
    @votes.count
  end

  def get_votes(post_id)
    @votes = Vote.all(:conditions => {:post_id => post_id})
  end

  def has_voted?(post_id)
    if Vote.all(:conditions => {:post_id => post_id, :user_id => session[:user_id]})
        return true
    else
      return false
    end
  end
end

backchannelapp/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <div id="new_post_form">
      <h3>Please post your question</h3>
       <%= f.text_area :message %>
    </div>

    <%#= text_field_tag :category, '', :size => 30, :placeholder => 'Category', :maxlength => 20%>
    <%= f.label :category_id %>
    <%= select("post", "category_id", Category.all.collect{ |c| [ c.category, c.id] }) %>
    <%#= f.select(:category, :id, Category.all.collect{ |c| [ c.category, c.id] }) %>
    <%#= f.select :category, options_for_select()%>
    <%#= f.collection_select @category %>

    <div id="submit_button_container">
      <%= f.submit "", :class => "button" %>
      <%#= f.submit "Post", :class => "button" %>
      <%#= f.submit "Post"  %>
    </div>
    <div class="clear"></div>
    </div>
<%- end -%>

backchannelapp/app/views/posts/_posts_list.html.erb
<ul id="posts_list">
  <% @all_posts.reverse.each do |post| %>
      <li <% if @all_posts.first == post %> class="first" <% end %>>
        <div class="post_message_container">
          <h3><%= link_to post.user.username, post.user %></h3>
          <%= link_to post.message, post %>
           <div class="time_ago">
            <%= distance_of_time_in_words_to_now(post.created_at)%> ago
          </div>
          <h4>
          <%#(post.category).split(/\s/).each do |c|  %>
            <%#= "##{c}"  %>
           <% #end %>
            #<%= "#{post.category.category}" %>
            <div class="edit_links">
            <p>
              <% if post.user.id == session[:user_id] || current_user.admin == 1%>
                  <p><%= button_to "Delete", post, :confirm => "Do you want to delete the post ?", :method => :delete%></p>
               <% end %>
            <% if post.user.id == session[:user_id] %>
                 <p><%= button_to "Edit", edit_post_path(post), :method => :get%></p>
            <% else %>
                <%#= button_to "Vote", new_vote_path, :post_id => post.id %>
                <% if can_vote?(post.id) %>
                    <%= button_to "Vote", :controller => :posts, :action => :create_vote, :post_id => post.id %>
                <% end %>
                <%# if post.commented == 0 %>
                      <%#= button_to "Comment", :controller => :comments, :action => :new, :id => post.id %>
                      <%= button_to "Comment", :controller => :comments, :action => :new, :post_id => post.id %>
                <%# end %>
            <% end %>
              <p>
              <%= render :partial => 'posts/votes', :locals => {:post => post} %>
             </p>
            </div>
          </h4>
        </div>
        <div class="clear"></div>
      </li>
  <%end%>
</ul>

backchannelapp/app/views/posts/_search.html.erb
<h2>Search Existing Posts</h2>
<%= form_tag :controller => 'posts', :action => 'search' do %>
    <%#= text_field_tag :category, params[:category], :size => 30, :placeholder => 'Category', :maxlength => 20%>
    <%#= text_field_tag :content, params[:content], :size => 30, :placeholder => 'Content', :maxlength => 20%>
    <%#= text_field_tag :username, params[:username], :size => 30, :placeholder => 'Username', :maxlength => 20%>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Search", :name => nil %>
<%end%>

backchannelapp/app/views/posts/_single.html.erb
<ul id="posts_list">
  <li class="first">
    <div class="post_message_container">
      <h3><%= @post.message %></h3>
      <div class="time_ago">
        <%= distance_of_time_in_words_to_now(@post.created_at)%> ago
      </div>
      <% if @post.user.id == session[:user_id] %>
          <h4>By: You</h4>
      <% else %>
          <h4>By: <%= @post.user.username %></h4>
      <% end %>
      <% post = @post %>
      <%= render :partial => 'posts/votes', :locals => {:post => post} %>
    </div>
  </li>
</ul>

backchannelapp/app/views/posts/_votes.html.erb
<%
    votes_count = num_votes(post.id)
    if votes_count == 1
     if can_vote?(post.id)
       output = "One person voted for this post"
     else
       output = "You voted for this post"
     end
    else if can_vote?(post.id)
      output = "#{votes_count} people voted for this post"
    else
      output = "You and #{votes_count-1} other people voted for this post"
    end
    end
%>
<p><%= link_to output, :controller => :votes, :action => :show, :post_id => post.id %></p>

backchannelapp/app/views/posts/edit.html.erb
<%title "Edit"  %>

<p>
  <%= link_to "Back", posts_path %>
</p>

<%= form_for @post do |f| %>
    <div id="new_post_form">
      <h3>Edit your question</h3>
      <%= f.text_area :message, :value => @post.message%>
    </div>

    <%#= text_field_tag :category, params[:category], :size => 30, :value => @post.category, :maxlength => 20%>

    <div id="submit_button_container">
      <%= f.submit "", :class => "button" %>
      <%#= f.submit "Post", :class => "button" %>
    </div>
    <div class="clear"></div>
    </div>
<%- end -%>

backchannelapp/app/views/posts/index.html.erb
<%title "Welcome to Back Channel #{current_user.username}"%>
<% if current_user.admin == 1 %>
    <%= link_to "Back", users_path %>
<% end %>
<p>
  <h2><%= link_to "Add a new post", new_post_path  %></h2>
</p>
<div>
  <%= render :partial => 'posts/search' %>
</div>

<%= render :partial => "posts_list", :locals => {:posts => @all_posts} %>

backchannelapp/app/views/posts/new.html.erb
<%title "New Post"%>

<%= render :partial => 'posts/form' %>

backchannelapp/app/views/posts/search.html.erb
<% title "Search results"%>
<%= link_to "Back", :back %>
<ul id="posts_list">
  <% @results.reverse.each do |post| %>
      <li class="first">
        <div class="post_message_container">
          <h3>
          <%# if logged_in? %>
                <%#= link_to post.user.username, post.user %>
           <%# else %>
          <%= post.user.username%>
           <%# end %>
          </h3>
          <% #if logged_in? %>
                <%#= link_to post.message, post %>
          <%# else %>
            <%= post.message%>
          <% #end %>
          <div class="time_ago">
            <%= distance_of_time_in_words_to_now(post.created_at)%> ago
          </div>
          <h4>
            #<%= "#{post.category.category}" %>

          </h4>
        </div>
        <div class="clear"></div>
      </li>

  <%end%>
</ul>

backchannelapp/app/views/posts/show.html.erb
<p>
  <%= link_to "Back", posts_path %>
</p>
<%title "Single post"  %>
<p>
<%= render :partial => "posts/single", :locals => {:posts => @post} %>
</p>
<br>
<p>

<% if @post.commented == 1%>
    <%= render :partial => "comments/show", :locals => {:comments => @comments} %>
<% end %>
</br>
</p>