backchannelapp/config/routes.rb
Backchannelapp::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :posts

  resources :comments

  resources :votes

  match 'posts/search',:to => 'posts#search'
  match 'users/report', :to => 'users#report'

  root :to => 'welcome#index'

   match ':controller(/:action(/:id))(.:format)'
end

backchannelapp/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :created_at, :post_id, :user_id
  belongs_to :user
  belongs_to :post
  has_many :commentvotes, :dependent => :destroy
  validates_presence_of :user_id, :post_id, :comment, :created_at
end

backchannelapp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index

  end

  def edit
    @current_comment = Comment.find(params[:id])
    @current_post = Post.find(@current_comment.post_id)
  end

  def update
    @current_comment = Comment.find(params[:id])
    @current_post = Post.find(@current_comment.post_id)
    @current_comment.update_attributes(:comment => params[:comment], :created_at => Time.now)
    respond_to do |format|
    if @current_comment.update_attributes(:comment => params[:comment], :created_at => Time.now)
        @current_post.update_attributes(:created_at => Time.now)
      format.html {redirect_to post_path(@current_comment.post_id), :notice => "Comment successfully updated"}
    else
      format.html {redirect_to post_path(@current_comment.post_id), :notice => "Failed to update Comment"}
    end
   end
  end

  def new
    @new_comment = Comment.new
    @current_post = Post.find(params[:post_id])
    respond_to do |format|
      format.html # new.html.erb
    end
  end
  def create
     @comment = Comment.new(:comment => params[:comment])
     @comment.user_id = session[:user_id]
     @current_post = Post.find(params[:post_id])
     @comment.post_id = @current_post.id
     @comment.created_at = Time.now

     respond_to do |format|
       if @comment.save
         @post = Post.find(params[:post_id])
         @post.update_attributes(:commented => 1, :created_at => Time.now)
         format.html {redirect_to post_path(@post), :notice => "Commented successfully"}
       else
         format.html {redirect_to post_path(@post), :notice => "Failed to submit comment"}
       end
     end
  end

  def create_vote
    @vote = Commentvote.new(:comment_id => params[:comment_id], :user_id => current_user.id, :created_at => Time.now)
    respond_to do |format|
      if @vote.save
        @comment = Comment.find(params[:comment_id])
        @comment.update_attributes(:created_at => Time.now)
        @post = Post.find(@comment.post_id)
        @post.update_attributes(:created_at => Time.now)
        format.html {redirect_to posts_path, :notice => "Voted for comment successfully"}
      else
        format.html {redirect_to posts_path, :notice => "Failed to vote comment"}
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    respond_to do |format|
    if @comment.destroy
      @post.update_attributes(:created_at => Time.now, :commented => 0)
      format.html {redirect_to :back, :notice => "Comment successfully deleted"}
    else
      format.html {redirect_to :back, :notice => "Comment to delete post"}
    end
    end
  end
end

backchannelapp/app/helpers/comments_helper.rb
module CommentsHelper
  def can_vote_comment?(comment_id)
    @votes = Commentvote.all(:conditions => {:comment_id => comment_id})
    @votes.each do |v|
      if v.user_id == session[:user_id]
        return false
      end
    end
    return true
  end

  def num_votes_comment(comment_id)
    @votes = Commentvote.all(:conditions => {:comment_id => comment_id})
    @votes.count
  end

  def get_votes_comment(comment_id)
    @votes = Commentvote.all(:conditions => {:comment_id => comment_id})
  end
end

backchannelapp/app/views/comments/_show.html.erb
<ul id="posts_list">
  <% @comments.each do |comment| %>
      <li <% if @comments.first == comment %> class="first" <% end %>>
      <div class="post_message_container">
           <h3><%= comment.comment %></h3>
            <div class="time_ago">
             <%= distance_of_time_in_words_to_now(comment.created_at)%> ago
        </div>
        <% if comment.user.id == session[:user_id] %>
            <h4>By: You</h4>
        <% else %>
            <h4>By: <%= comment.user.username %></h4>
        <% end %>
        <div class="edit_links">
        <% if comment.user.id == session[:user_id] || current_user.admin == 1%>
            <p><%= button_to "Delete", comment, :confirm => "Do you want to delete the post ?", :method => :delete, :id => comment.id%></p>
        <% end %>
        <% if comment.user.id == session[:user_id] %>
             <p>
             <%#= button_to "Edit", :controller => :comments, :action => :edit, :method => :get, :id => @comment[0].id%>
             <%= button_to "Edit", edit_comment_path(comment), :method => :get%>
             <%#= button_to "Delete", :controller => :comments, :action => :destroy, :confirm => "Do you want to delete the comment ?", :method => :delete, :id => @comment[0].id%>
             </p>
         <% else %>
            <% if can_vote_comment?(comment.id) %>
                <%= button_to "Vote", :controller => :comments, :action => :create_vote, :comment_id => comment.id %>
            <% end %>
            <% end %>
        </div>
        <%
           #votes = get_votes_comment(@comment[0].id)
           votes_count = num_votes_comment(comment.id)
           if votes_count == 1
             if can_vote_comment?(comment.id)
                     output = "One person voted for this comment"
             else
                     output = "You voted for this comment"
             end
           else if can_vote_comment?(comment.id)
                  output = "#{votes_count} people voted for this comment"
                else
                  output = "You and #{votes_count-1} other people voted for this comment"
                end
           end
        %>
        <p><%= link_to output, :controller => :commentvotes, :action => :show, :comment_id => comment.id %></p>
      </div>
        <div class="clear"></div>
    </li>
  <% end %>
</ul>

backchannelapp/app/views/comments/edit.html.erb
<%title "Edit comment"%>

<p>
  <%= link_to "Back", post_path(@current_comment.post_id) %>
</p>
<h3>
  <p><%= @current_post.message %></p>
</h3>
<%= form_for @current_comment do |f|%>
    <div id="new_post_form">
      <h3>Edit your comment</h3>
      <%= text_area_tag :comment, params[:comment], :values => @current_comment.comment%>
    </div>
    <div id="submit_button_container">
      <%= f.submit "", :class => "button"%>
    </div>
    <div class="clear"></div>
    </div>
<% end %>

backchannelapp/app/views/comments/new.html.erb
<%title "Add comment"%>

<h2>Commenting on Post:</h2>
<h3>
<p><%= @current_post.message %></p>
</h3>
<%= form_for @new_comment do |f| %>
    <div id="new_post_form">
      <h3><%= f.label :comment %></h3>
      <%= text_area_tag :comment, params[:comment]%>
    </div>
    <div>
    <%= hidden_field_tag :post_id, @current_post.id %>
    </div>
    <div id="submit_button_container">
      <%= f.submit "", :class => "button"%>
    </div>
    <div class="clear"></div>
    </div>
<%- end -%>