backchannelapp/config/routes.rb
Backchannelapp::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :posts

  resources :comments

  resources :votes

  match 'posts/search',:to => 'posts#search'
  match 'users/report', :to => 'users#report'

  root :to => 'welcome#index'

   match ':controller(/:action(/:id))(.:format)'
end

backchannelapp/app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation, :admin

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  has_many :commentvotes, :dependent => :destroy
  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

backchannelapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.admin = 0
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to_target_or_default :controller => '/posts', :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end

  def show
    @usr = User.find(params[:id])

  end

  def index
    @users = User.all
    @category = Category.all
  end

  def delete_user
     @user = User.find(params[:user_id])
     if @user.destroy
       redirect_to users_path, :notice => "User deleted."
     else
       redirect_to users_path, :notice => "Unable to delete user."
     end
  end

  def make_admin
    @user = User.find(params[:user_id])
    if @user.update_attributes(:admin => 1)
      redirect_to users_path, :notice => "User has been made admin."
    else
      redirect_to users_path, :notice => "Unable to save user."
    end
  end

  def revoke_admin
    @user = User.find(params[:user_id])
    if @user.update_attributes(:admin => 0)
      redirect_to users_path, :notice => "User has been revoked admin rights."
    else
      redirect_to users_path, :notice => "Unable to save user."
    end
  end

  def add_category
    @category = Category.new
    @category.category = params[:new]
    if @category.save
      redirect_to users_path, :notice => "Category has been added."
    else
      redirect_to users_path, :notice => "Failed to add category."
    end
  end

  def delete_category
    @category = Category.find(params[:category_id])
    if @category.destroy
      redirect_to users_path, :notice => "Category has been deleted."
    else
      redirect_to users_path, :notice => "Unable to delete category."
    end
  end

  def report
    @users = User.all
  end
end

backchannelapp/app/helpers/users_helper.rb
module UsersHelper

  def user_get_posts(user_id)
      Post.all(:conditions => {:user_id => user_id}).count
  end

  def user_get_votes_posts(user_id)
    count = 0
    @post = Post.all(:conditions => {:user_id => user_id})
    @post.each do |p|
      count += Vote.all(:conditions => {:post_id => p.id}).count
    end
    count
  end

  def user_get_comments_post(user_id)
    count = 0
    @post = Post.all(:conditions => {:user_id => user_id})
    @post.each do |p|
      count += p.commented
    end
    count
  end

  def user_get_comments_votes(user_id)
    count = 0
    @comments = Comment.all(:conditions => {:user_id => user_id})
    @comments.each do |c|
      count += Commentvote.all(:conditions => {:comment_id => c.id}).count
    end
    count
  end

  def user_post_voted(user_id)
    Vote.all(:conditions => {:user_id => user_id}).count
  end

  def user_total_comments(user_id)
    Comment.all(:conditions => {:user_id => user_id}).count
  end

  def user_comments_voted(user_id)
    Commentvote.all(:conditions => {:user_id => user_id}).count
  end
end

backchannelapp/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

backchannelapp/app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

backchannelapp/app/views/users/index.html.erb
<%title "Admin page"%>
<p>
<h3><%= link_to "List of Posts", posts_path%></h3>
</p>
<p><%= button_to "Generate report", :controller => :users, :action => :report%></p>
<p>
<h3>List of Categories: </h3>
    <% @category.each do |c| %>
        <h4><p><%= c.category %></p></h4>
        <%= button_to "Delete Category", :method => :delete, :controller => :users, :action => :delete_category, :category_id => c.id %>
    <% end %>
</p>
<%#= text_field_tag :new, params[:new]%>
<%#= button_to "Add a new Category", :controller => :users, :action => :add_category, :new => params[:new]%>
<%= form_tag :controller => :users, :action => :add_category do %>
    <%= text_field_tag :new, params[:new]%>
    <%= submit_tag "Add Category", :name => nil %>
<%end%>
<br>
<p><h3>List of Users:</h3></p>

<p>
<ul id="posts_list">
  <% @users.each do |user| %>
      <li>
      <div class="post_message_container">
           <h3><%= user.username %></h3>
            <div class="time_ago">
            Created <%= distance_of_time_in_words_to_now(user.created_at)%> ago
            </div>
            <% if current_user.admin == 1 %>
            <p>
              <% if user.admin == 0 %>
                <%= button_to "Make admin", :controller => :users, :action => :make_admin, :user_id => user.id%>
                <% else %>
                  <%= button_to "Revoke admin rights", :controller => :users, :action => :make_admin, :user_id => user.id%>
               <% end %>
              <%= button_to "Delete", :controller => :users, :action => :delete_user, :confirm => "Do you want to delete the user ?", :method => :delete, :user_id => user.id%>
            </p>
             <% end %>

        </div>
       <div class="clear"></div>
      </li>
  <% end %>
</ul>
</p>

backchannelapp/app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

backchannelapp/app/views/users/report.html.erb
<%title "Report"%>
<table>
  <tr>
    <th>User</th>
    <th>Total Posts Posted</th>
    <th>Total Votes on his Posts</th>
    <th>Total Comments on his Posts</th>
    <th>Total Votes on his Comments </th>
    <th>Total Posts voted</th>
    <th>Total Posts commented</th>
    <th>Total Comments Voted</th>
    <th></th>
    <th></th>
  </tr>

    <% @users.each do |user| %>
        <tr>
           <td><%= user.username %></td>
           <td><%= user_get_posts(user.id) %></td>
           <td><%= user_get_votes_posts(user.id) %></td>
           <td><%= user_get_comments_post(user.id) %></td>
           <td><%= user_get_comments_votes(user.id) %></td>
           <td><%= user_post_voted(user.id) %></td>
           <td><%= user_total_comments(user.id) %></td>
           <td><%= user_comments_voted(user.id) %></td>
           <td></td>
        </tr>

    <% end %>

</table>
<%= link_to "Back", users_path %>

backchannelapp/app/views/users/show.html.erb
<p>
  <%= link_to "Back", :back %>
</p>
<h2><%= @usr.username%></h2>

<p>
 <h3>Created on: <%= @usr.created_at %></h3>
</p>